// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/contract-workspace-redesign/ActionItems.tsx": () => import("../components/mockups/contract-workspace-redesign/ActionItems.tsx"),
  "./components/mockups/contract-workspace-redesign/IssueReview.tsx": () => import("../components/mockups/contract-workspace-redesign/IssueReview.tsx"),
  "./components/mockups/contract-workspace-redesign/Overview.tsx": () => import("../components/mockups/contract-workspace-redesign/Overview.tsx")
};
