import { ArrowRight, CalendarClock, Check, Mail, MoreHorizontal, UserRound } from "lucide-react";
import { AppShell, Pill } from "./_shared/AppShell";

const items = [
  { tone:"critical" as const, label:"Confirm notice path", vendor:"Northstar Analytics", detail:"Notice deadline is 14 Mar · 17 days left", owner:"Maya Chen", type:"Decision", date:"Today" },
  { tone:"watch" as const, label:"Approve uplift response", vendor:"Juniper Health", detail:"Vendor proposed 8.5% increase at renewal", owner:"Ravi Shah", type:"Approval", date:"Thu, 27 Feb" },
  { tone:"watch" as const, label:"Assign commercial owner", vendor:"Porter Freight", detail:"Renewal is 18 Jul · owner is unconfirmed", owner:"Unassigned", type:"Assignment", date:"03 Mar" },
  { tone:"neutral" as const, label:"Attach missing exhibit", vendor:"Kestrel Cloud", detail:"Security schedule referenced but not in family", owner:"Ravi Shah", type:"Missing data", date:"07 Mar" },
];
export function ActionItems() { return <AppShell active="actions" eyebrow="Action queue / 5 open" title="The next right moves." subtitle="A short list of decisions that keep renewal work moving. No duplicate contract detail.">
  <div id="queue" className="grid lg:grid-cols-[1fr_300px] gap-5">
    <section className="bg-[#fbfcf8] border hairline rounded-xl overflow-hidden"><div className="px-5 py-4 border-b hairline flex items-center justify-between"><div><h2 className="font-extrabold text-sm">Open queue</h2><p className="text-[11px] text-[#7b8d86] mt-1">4 items need a human decision</p></div><Pill tone="critical">2 due this week</Pill></div><div className="divide-y divide-[#e4eae3]">{items.map((item,i)=><article key={item.label} className="row-hover px-5 py-4 flex gap-4 items-start"><div className={`mt-1 h-8 w-8 shrink-0 rounded-lg grid place-items-center ${item.tone==="critical"?"bg-[#fbe9e4] text-[#c95143]":item.tone==="watch"?"bg-[#f7efd9] text-[#a57926]":"bg-[#e9efeb] text-[#627b72]"}`}>{item.tone==="critical"?<CalendarClock size={16}/>:item.type==="Missing data"?<Mail size={15}/>:<Check size={16}/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-[13px] font-extrabold">{item.label}</h3><span className="text-[9px] uppercase tracking-[.1em] font-extrabold text-[#84938e]">{item.type}</span></div><div className="text-[12px] font-semibold text-[#4f6660] mt-1">{item.vendor}</div><div className="text-[11px] text-[#83918c] mt-1">{item.detail}</div><div className="flex items-center gap-3 mt-3 text-[10px] font-bold text-[#758780]"><span className="flex items-center gap-1"><UserRound size={12}/>{item.owner}</span><span className="text-[#c3ccc6]">·</span><span className={i===0?"text-[#b54438]":""}>{item.date}</span></div></div><div className="flex items-center gap-2 shrink-0"><button className="hidden sm:flex h-8 items-center gap-1.5 rounded-md bg-[#176b67] px-3 text-[11px] font-extrabold text-white hover:bg-[#125955]">Open <ArrowRight size={13}/></button><button className="h-8 w-8 grid place-items-center rounded-md text-[#82918b] hover:bg-[#edf3ed]"><MoreHorizontal size={16}/></button></div></article>)}</div></section>
    <aside className="space-y-4"><div className="rounded-xl bg-[#173f3c] text-[#eff8f0] p-5"><div className="mono text-[10px] uppercase tracking-[.15em] text-[#a8d4c3]">Queue health</div><div className="text-4xl font-extrabold tracking-[-.07em] mt-3">86<span className="text-lg">%</span></div><p className="text-[11px] text-[#b8d0c7] mt-1">of work is on track this week</p><div className="h-1.5 rounded-full bg-[#355d56] mt-5 overflow-hidden"><div className="h-full w-[86%] bg-[#8ed0b7] rounded-full"/></div></div><div className="bg-[#fbfcf8] border hairline rounded-xl p-5"><div className="flex items-center justify-between"><h3 className="font-extrabold text-sm">Recently resolved</h3><span className="mono text-[10px] text-[#83918c]">LAST 7D</span></div><div className="mt-4 space-y-4"><div className="flex gap-2.5"><span className="h-5 w-5 rounded-full bg-[#e1f0ed] text-[#247267] grid place-items-center"><Check size={12}/></span><div><div className="text-[11px] font-bold">Confirmed billing basis</div><div className="text-[10px] text-[#83918c]">Lattice & Co. · yesterday</div></div></div><div className="flex gap-2.5"><span className="h-5 w-5 rounded-full bg-[#e1f0ed] text-[#247267] grid place-items-center"><Check size={12}/></span><div><div className="text-[11px] font-bold">Assigned renewal owner</div><div className="text-[10px] text-[#83918c]">Bluebird Office · 4d ago</div></div></div></div></div></aside>
  </div>
</AppShell> }