import { Check, ChevronDown, FileText, MessageSquare, Sparkles, X } from "lucide-react";
import { useState } from "react";
import { AppShell, Pill } from "./_shared/AppShell";

const issues = [
  { id:1, kind:"Ambiguous", title:"Renewal notice period", copy:"Two extracted clauses imply different notice windows.", evidence:"30 days before each term end", options:["30 days before term end","60 days before term end"] },
  { id:2, kind:"Missing data", title:"Contract value basis", copy:"The agreement states a fee, but does not say whether it is annual or total.", evidence:"$184,000 fee", options:["Annual recurring","Total contract value"] },
  { id:3, kind:"Risk", title:"Termination for convenience", copy:"No unilateral termination right was detected in the extracted clauses.", evidence:"No matching clause found", options:["Not present","Present — add clause reference"] },
];
export function IssueReview() {
 const [resolved,setResolved]=useState<number[]>([]); const [expanded,setExpanded]=useState(false); const [selected,setSelected]=useState<Record<number,string>>({});
 const resolve=(id:number)=>setResolved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 return <AppShell active="review" eyebrow="Issue review / Northstar Analytics" title="Resolve the uncertainty." subtitle="Three focused decisions stand between this family and a trustworthy renewal plan.">
   <div id="review" className="flex flex-wrap items-center justify-between gap-3 mb-5"><div className="flex items-center gap-3"><div className="h-10 w-10 rounded-xl bg-[#e2eee8] text-[#176b67] grid place-items-center"><FileText size={19}/></div><div><div className="font-extrabold text-sm">Northstar Analytics — MSA</div><div className="text-[11px] text-[#7c8c87] mt-1">2 documents · amended 18 Jan 2024 · $184,000 / yr</div></div></div><button className="h-9 rounded-md bg-[#176b67] text-white px-4 text-xs font-extrabold flex items-center gap-2 hover:bg-[#125955]"><Check size={14}/> Save review</button></div>
   <div className="grid lg:grid-cols-[1fr_310px] gap-5 items-start"><section className="space-y-3">{issues.map(issue=>{const done=resolved.includes(issue.id); return <article key={issue.id} className={`bg-[#fbfcf8] border rounded-xl p-5 transition-colors ${done?"border-[#a9d1c2] bg-[#f4faf5]":"hairline"}`}><div className="flex gap-3"><div className={`mt-0.5 h-7 w-7 shrink-0 rounded-full grid place-items-center ${done?"bg-[#d8eee3] text-[#287764]":issue.kind==="Risk"?"bg-[#fbe9e4] text-[#c95143]":"bg-[#f7efd9] text-[#a57926]"}`}>{done?<Check size={14}/>:issue.kind==="Risk"?<X size={14}/>:<Sparkles size={14}/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`text-[9px] font-extrabold uppercase tracking-[.12em] ${done?"text-[#287764]":issue.kind==="Risk"?"text-[#b54438]":"text-[#9a7429]"}`}>{done?"Resolved":issue.kind}</span><span className="mono text-[10px] text-[#9aa6a1]">ISSUE 0{issue.id}</span></div><h2 className={`font-extrabold text-[15px] mt-1 ${done?"text-[#66827a] line-through":""}`}>{issue.title}</h2><p className="text-[12px] text-[#60736d] mt-1.5 leading-relaxed">{issue.copy}</p><div className="mt-3 rounded-lg bg-[#f1f5ef] border hairline px-3 py-2.5 text-[11px] font-semibold text-[#536963]"><span className="text-[9px] uppercase tracking-[.12em] text-[#8b9a94] mr-2">Evidence</span>“{issue.evidence}”</div>{!done&&<div className="mt-3 flex flex-wrap gap-2">{issue.options.map(opt=><button key={opt} onClick={()=>setSelected({...selected,[issue.id]:opt})} className={`rounded-md border px-3 py-2 text-[11px] font-bold text-left transition-colors ${selected[issue.id]===opt?"border-[#176b67] bg-[#e1f0ed] text-[#176b67]":"hairline hover:bg-[#edf3ed]"}`}>{opt}</button>)}<button onClick={()=>resolve(issue.id)} disabled={!selected[issue.id]} className="ml-auto rounded-md bg-[#173f3c] text-white px-3 py-2 text-[11px] font-extrabold disabled:opacity-35 hover:bg-[#125955]">Resolve</button></div>}</div></div></article>})}</section>
   <aside className="space-y-4"><div className="bg-[#fbfcf8] border hairline rounded-xl p-5"><div className="flex items-center justify-between"><h3 className="font-extrabold text-sm">Review progress</h3><Pill tone={resolved.length===3?"healthy":"watch"}>{resolved.length}/3 resolved</Pill></div><div className="flex gap-1.5 mt-4">{[1,2,3].map(n=><div key={n} className={`h-1.5 flex-1 rounded-full ${resolved.includes(n)?"bg-[#4a9d7e]":"bg-[#dfe8e1]"}`}/>)}</div><p className="text-[11px] text-[#71837d] mt-4">{resolved.length===3?"All decision points are resolved.":"Resolve only the flagged points; confirmed fields stay out of your way."}</p></div><div className="bg-[#fbfcf8] border hairline rounded-xl overflow-hidden"><button onClick={()=>setExpanded(!expanded)} className="w-full px-5 py-4 flex items-center justify-between text-left hover:bg-[#f1f5ef]"><div><div className="font-extrabold text-sm">Full extraction</div><div className="text-[10px] text-[#82918c] mt-1">18 confirmed fields · secondary view</div></div><ChevronDown size={16} className={`text-[#71827b] transition-transform ${expanded?"rotate-180":""}`}/></button>{expanded&&<div className="border-t hairline p-4 space-y-2 text-[11px]"><div className="flex justify-between"><span className="text-[#81918b]">Vendor legal name</span><b>Northstar Analytics, Inc.</b></div><div className="flex justify-between"><span className="text-[#81918b]">Effective date</span><b>15 Mar 2022</b></div><div className="flex justify-between"><span className="text-[#81918b]">Billing frequency</span><b>Annual</b></div><div className="flex justify-between"><span className="text-[#81918b]">Document language</span><b>English</b></div></div>}</div><button className="w-full rounded-xl border hairline bg-[#fbfcf8] p-4 flex items-center gap-3 text-left hover:bg-[#edf3ed]"><MessageSquare size={16} className="text-[#176b67]"/><div><div className="text-xs font-extrabold">Leave a review note</div><div className="text-[10px] text-[#82918c] mt-1">Add context for Legal or Finance</div></div></button></aside></div>
 </AppShell>
}