import { ArrowUpRight, ChevronRight, Filter, Plus, Search, SlidersHorizontal } from "lucide-react";
import { AppShell, contracts, Pill } from "./_shared/AppShell";

export function Overview() {
  return <AppShell active="overview" eyebrow="Portfolio / Q1 2025" title="Know what can’t wait." subtitle="A single operating view of 28 active contract families, renewal exposure, and unresolved extraction issues.">
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-7">
      {[["28","Active families","neutral"],["$4.8m","Annualized value","healthy"],["3","Notice windows","critical"],["5","Open decisions","watch"]].map(([value,label,tone])=><div key={label} className="bg-[#fbfcf8] border hairline rounded-xl p-4"><div className={`text-[25px] font-extrabold tracking-[-.06em] ${tone==="critical"?"text-[#b54438]":tone==="watch"?"text-[#956b20]":"text-[#173f3c]"}`}>{value}</div><div className="text-[11px] font-bold text-[#71827b] mt-1">{label}</div></div>)}
    </div>
    <section className="bg-[#fbfcf8] border hairline rounded-xl overflow-hidden shadow-[0_10px_30px_rgba(46,77,62,.05)]">
      <div className="px-4 sm:px-5 py-4 border-b hairline flex flex-wrap items-center gap-3 justify-between"><div className="flex items-center gap-2"><h2 className="font-extrabold text-sm">Contract families</h2><span className="mono text-[10px] text-[#7b8d86]">07 / 28 shown</span></div><div className="flex items-center gap-2"><div className="relative hidden sm:block"><Search size={14} className="absolute left-3 top-2.5 text-[#8ca09a]"/><input className="h-8 w-44 rounded-md border hairline bg-[#f4f7f2] pl-8 pr-3 text-xs outline-none focus:border-[#6da99c]" placeholder="Find a family…"/></div><button className="h-8 px-2.5 rounded-md border hairline text-[#60746e] hover:bg-[#edf3ed]"><Filter size={14}/></button><button className="h-8 px-2.5 rounded-md bg-[#176b67] text-white text-xs font-bold flex items-center gap-1.5 hover:bg-[#125955]"><Plus size={14}/> Add contract</button></div></div>
      <div className="overflow-x-auto"><table className="w-full text-left min-w-[850px]"><thead className="bg-[#f1f5ef] text-[10px] uppercase tracking-[.12em] text-[#81918b]"><tr><th className="px-5 py-3 font-extrabold">Family / commercial context</th><th className="px-3 py-3 font-extrabold">Renewal</th><th className="px-3 py-3 font-extrabold">Notice runway</th><th className="px-3 py-3 font-extrabold">Owner</th><th className="px-3 py-3 font-extrabold">Signal</th><th className="px-5 py-3"/></tr></thead><tbody className="divide-y divide-[#e4eae3]">{contracts.map((c)=><tr key={c.name} className="row-hover"><td className="px-5 py-3.5"><div className="flex items-center gap-3"><div className="h-8 w-8 rounded-lg bg-[#e3eee7] text-[#286860] grid place-items-center text-[10px] font-extrabold">{c.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><div className="text-[13px] font-extrabold">{c.name}</div><div className="text-[11px] text-[#778983] mt-0.5">{c.type} <span className="mx-1 text-[#b6c3bc]">·</span><span className="mono text-[10px]">{c.value}</span></div></div></div></td><td className="px-3 py-3.5"><div className="text-xs font-bold">{c.renewal}</div><div className="text-[10px] text-[#85958e] mt-0.5">Auto-renewal</div></td><td className="px-3 py-3.5"><span className={`mono text-[11px] font-medium ${c.status==="critical"?"text-[#b54438]":c.status==="watch"?"text-[#956b20]":"text-[#53736b]"}`}>{c.notice}</span></td><td className="px-3 py-3.5"><div className="flex items-center gap-2 text-xs font-bold"><span className="h-6 w-6 rounded-full bg-[#dce8df] grid place-items-center text-[9px]">{c.initials}</span>{c.owner}</div></td><td className="px-3 py-3.5"><Pill tone={c.status as "critical"|"watch"|"healthy"}>{c.issues ? `${c.issues} issue${c.issues>1?"s":""}` : c.tag}</Pill></td><td className="px-5 py-3.5 text-right"><button className="h-7 w-7 grid place-items-center rounded-md text-[#71827b] hover:bg-[#e4eee7] hover:text-[#176b67]" title="Open family"><ChevronRight size={16}/></button></td></tr>)}</tbody></table></div>
      <div className="px-5 py-3 border-t hairline flex items-center justify-between text-[11px] text-[#81918b]"><span>Showing highest exposure first</span><button className="font-bold text-[#176b67] hover:underline flex items-center gap-1">View all families <ArrowUpRight size={13}/></button></div>
    </section>
    <div className="mt-4 flex items-center gap-2 text-[11px] text-[#80908a]"><SlidersHorizontal size={13}/> <span>View is sorted by nearest decision point</span><button className="ml-auto underline hover:text-[#176b67]">Adjust columns</button></div>
  </AppShell>
}